apiVersion: oracle-autonomous-database.oraclead.m.crossplane.io/v1alpha1
kind: AutonomousDatabase
metadata:
  annotations:
    meta.upbound.io/example-id: oracle-autonomous-database/v1alpha1/autonomousdatabase
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: crossplane-system
spec:
  forProvider:
    adminPasswordSecretRef:
      key: example-key
      name: example-secret
    autoScalingEnabled: example
    autoScalingForStorageEnabled: false
    backupRetentionPeriodInDays: 42
    characterSet: example
    computeCount: 1.23456
    computeModel: example
    data_storage_size_in_gbs: 42
    dbVersion: example
    dbWorkload: example
    displayName: example
    licenseModel: false
    location: West Europe
    mtlsConnectionRequired: false
    nationalCharacterSet: example
    resourceGroupName: example
    subnetId: example
    virtualNetworkId: example
