//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutonomousDatabase) DeepCopyInto(out *AutonomousDatabase) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutonomousDatabase.
func (in *AutonomousDatabase) DeepCopy() *AutonomousDatabase {
	if in == nil {
		return nil
	}
	out := new(AutonomousDatabase)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AutonomousDatabase) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutonomousDatabaseInitParameters) DeepCopyInto(out *AutonomousDatabaseInitParameters) {
	*out = *in
	in.AdminPasswordSecretRef.DeepCopyInto(&out.AdminPasswordSecretRef)
	if in.AllowedIps != nil {
		in, out := &in.AllowedIps, &out.AllowedIps
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.AutoScalingEnabled != nil {
		in, out := &in.AutoScalingEnabled, &out.AutoScalingEnabled
		*out = new(bool)
		**out = **in
	}
	if in.AutoScalingForStorageEnabled != nil {
		in, out := &in.AutoScalingForStorageEnabled, &out.AutoScalingForStorageEnabled
		*out = new(bool)
		**out = **in
	}
	if in.BackupRetentionPeriodInDays != nil {
		in, out := &in.BackupRetentionPeriodInDays, &out.BackupRetentionPeriodInDays
		*out = new(float64)
		**out = **in
	}
	if in.CharacterSet != nil {
		in, out := &in.CharacterSet, &out.CharacterSet
		*out = new(string)
		**out = **in
	}
	if in.ComputeCount != nil {
		in, out := &in.ComputeCount, &out.ComputeCount
		*out = new(float64)
		**out = **in
	}
	if in.ComputeModel != nil {
		in, out := &in.ComputeModel, &out.ComputeModel
		*out = new(string)
		**out = **in
	}
	if in.CustomerContacts != nil {
		in, out := &in.CustomerContacts, &out.CustomerContacts
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.DBVersion != nil {
		in, out := &in.DBVersion, &out.DBVersion
		*out = new(string)
		**out = **in
	}
	if in.DBWorkload != nil {
		in, out := &in.DBWorkload, &out.DBWorkload
		*out = new(string)
		**out = **in
	}
	if in.DataStorageSizeInTbs != nil {
		in, out := &in.DataStorageSizeInTbs, &out.DataStorageSizeInTbs
		*out = new(float64)
		**out = **in
	}
	if in.DisplayName != nil {
		in, out := &in.DisplayName, &out.DisplayName
		*out = new(string)
		**out = **in
	}
	if in.LicenseModel != nil {
		in, out := &in.LicenseModel, &out.LicenseModel
		*out = new(string)
		**out = **in
	}
	if in.Location != nil {
		in, out := &in.Location, &out.Location
		*out = new(string)
		**out = **in
	}
	if in.LongTermBackupSchedule != nil {
		in, out := &in.LongTermBackupSchedule, &out.LongTermBackupSchedule
		*out = make([]LongTermBackupScheduleInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.MtlsConnectionRequired != nil {
		in, out := &in.MtlsConnectionRequired, &out.MtlsConnectionRequired
		*out = new(bool)
		**out = **in
	}
	if in.NationalCharacterSet != nil {
		in, out := &in.NationalCharacterSet, &out.NationalCharacterSet
		*out = new(string)
		**out = **in
	}
	if in.ResourceGroupName != nil {
		in, out := &in.ResourceGroupName, &out.ResourceGroupName
		*out = new(string)
		**out = **in
	}
	if in.SubnetID != nil {
		in, out := &in.SubnetID, &out.SubnetID
		*out = new(string)
		**out = **in
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.VirtualNetworkID != nil {
		in, out := &in.VirtualNetworkID, &out.VirtualNetworkID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutonomousDatabaseInitParameters.
func (in *AutonomousDatabaseInitParameters) DeepCopy() *AutonomousDatabaseInitParameters {
	if in == nil {
		return nil
	}
	out := new(AutonomousDatabaseInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutonomousDatabaseList) DeepCopyInto(out *AutonomousDatabaseList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AutonomousDatabase, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutonomousDatabaseList.
func (in *AutonomousDatabaseList) DeepCopy() *AutonomousDatabaseList {
	if in == nil {
		return nil
	}
	out := new(AutonomousDatabaseList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AutonomousDatabaseList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutonomousDatabaseObservation) DeepCopyInto(out *AutonomousDatabaseObservation) {
	*out = *in
	if in.AllowedIps != nil {
		in, out := &in.AllowedIps, &out.AllowedIps
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.AutoScalingEnabled != nil {
		in, out := &in.AutoScalingEnabled, &out.AutoScalingEnabled
		*out = new(bool)
		**out = **in
	}
	if in.AutoScalingForStorageEnabled != nil {
		in, out := &in.AutoScalingForStorageEnabled, &out.AutoScalingForStorageEnabled
		*out = new(bool)
		**out = **in
	}
	if in.BackupRetentionPeriodInDays != nil {
		in, out := &in.BackupRetentionPeriodInDays, &out.BackupRetentionPeriodInDays
		*out = new(float64)
		**out = **in
	}
	if in.CharacterSet != nil {
		in, out := &in.CharacterSet, &out.CharacterSet
		*out = new(string)
		**out = **in
	}
	if in.ComputeCount != nil {
		in, out := &in.ComputeCount, &out.ComputeCount
		*out = new(float64)
		**out = **in
	}
	if in.ComputeModel != nil {
		in, out := &in.ComputeModel, &out.ComputeModel
		*out = new(string)
		**out = **in
	}
	if in.CustomerContacts != nil {
		in, out := &in.CustomerContacts, &out.CustomerContacts
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.DBVersion != nil {
		in, out := &in.DBVersion, &out.DBVersion
		*out = new(string)
		**out = **in
	}
	if in.DBWorkload != nil {
		in, out := &in.DBWorkload, &out.DBWorkload
		*out = new(string)
		**out = **in
	}
	if in.DataStorageSizeInTbs != nil {
		in, out := &in.DataStorageSizeInTbs, &out.DataStorageSizeInTbs
		*out = new(float64)
		**out = **in
	}
	if in.DisplayName != nil {
		in, out := &in.DisplayName, &out.DisplayName
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.LicenseModel != nil {
		in, out := &in.LicenseModel, &out.LicenseModel
		*out = new(string)
		**out = **in
	}
	if in.Location != nil {
		in, out := &in.Location, &out.Location
		*out = new(string)
		**out = **in
	}
	if in.LongTermBackupSchedule != nil {
		in, out := &in.LongTermBackupSchedule, &out.LongTermBackupSchedule
		*out = make([]LongTermBackupScheduleObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.MtlsConnectionRequired != nil {
		in, out := &in.MtlsConnectionRequired, &out.MtlsConnectionRequired
		*out = new(bool)
		**out = **in
	}
	if in.NationalCharacterSet != nil {
		in, out := &in.NationalCharacterSet, &out.NationalCharacterSet
		*out = new(string)
		**out = **in
	}
	if in.ResourceGroupName != nil {
		in, out := &in.ResourceGroupName, &out.ResourceGroupName
		*out = new(string)
		**out = **in
	}
	if in.SubnetID != nil {
		in, out := &in.SubnetID, &out.SubnetID
		*out = new(string)
		**out = **in
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.VirtualNetworkID != nil {
		in, out := &in.VirtualNetworkID, &out.VirtualNetworkID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutonomousDatabaseObservation.
func (in *AutonomousDatabaseObservation) DeepCopy() *AutonomousDatabaseObservation {
	if in == nil {
		return nil
	}
	out := new(AutonomousDatabaseObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutonomousDatabaseParameters) DeepCopyInto(out *AutonomousDatabaseParameters) {
	*out = *in
	in.AdminPasswordSecretRef.DeepCopyInto(&out.AdminPasswordSecretRef)
	if in.AllowedIps != nil {
		in, out := &in.AllowedIps, &out.AllowedIps
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.AutoScalingEnabled != nil {
		in, out := &in.AutoScalingEnabled, &out.AutoScalingEnabled
		*out = new(bool)
		**out = **in
	}
	if in.AutoScalingForStorageEnabled != nil {
		in, out := &in.AutoScalingForStorageEnabled, &out.AutoScalingForStorageEnabled
		*out = new(bool)
		**out = **in
	}
	if in.BackupRetentionPeriodInDays != nil {
		in, out := &in.BackupRetentionPeriodInDays, &out.BackupRetentionPeriodInDays
		*out = new(float64)
		**out = **in
	}
	if in.CharacterSet != nil {
		in, out := &in.CharacterSet, &out.CharacterSet
		*out = new(string)
		**out = **in
	}
	if in.ComputeCount != nil {
		in, out := &in.ComputeCount, &out.ComputeCount
		*out = new(float64)
		**out = **in
	}
	if in.ComputeModel != nil {
		in, out := &in.ComputeModel, &out.ComputeModel
		*out = new(string)
		**out = **in
	}
	if in.CustomerContacts != nil {
		in, out := &in.CustomerContacts, &out.CustomerContacts
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.DBVersion != nil {
		in, out := &in.DBVersion, &out.DBVersion
		*out = new(string)
		**out = **in
	}
	if in.DBWorkload != nil {
		in, out := &in.DBWorkload, &out.DBWorkload
		*out = new(string)
		**out = **in
	}
	if in.DataStorageSizeInTbs != nil {
		in, out := &in.DataStorageSizeInTbs, &out.DataStorageSizeInTbs
		*out = new(float64)
		**out = **in
	}
	if in.DisplayName != nil {
		in, out := &in.DisplayName, &out.DisplayName
		*out = new(string)
		**out = **in
	}
	if in.LicenseModel != nil {
		in, out := &in.LicenseModel, &out.LicenseModel
		*out = new(string)
		**out = **in
	}
	if in.Location != nil {
		in, out := &in.Location, &out.Location
		*out = new(string)
		**out = **in
	}
	if in.LongTermBackupSchedule != nil {
		in, out := &in.LongTermBackupSchedule, &out.LongTermBackupSchedule
		*out = make([]LongTermBackupScheduleParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.MtlsConnectionRequired != nil {
		in, out := &in.MtlsConnectionRequired, &out.MtlsConnectionRequired
		*out = new(bool)
		**out = **in
	}
	if in.NationalCharacterSet != nil {
		in, out := &in.NationalCharacterSet, &out.NationalCharacterSet
		*out = new(string)
		**out = **in
	}
	if in.ResourceGroupName != nil {
		in, out := &in.ResourceGroupName, &out.ResourceGroupName
		*out = new(string)
		**out = **in
	}
	if in.SubnetID != nil {
		in, out := &in.SubnetID, &out.SubnetID
		*out = new(string)
		**out = **in
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.VirtualNetworkID != nil {
		in, out := &in.VirtualNetworkID, &out.VirtualNetworkID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutonomousDatabaseParameters.
func (in *AutonomousDatabaseParameters) DeepCopy() *AutonomousDatabaseParameters {
	if in == nil {
		return nil
	}
	out := new(AutonomousDatabaseParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutonomousDatabaseSpec) DeepCopyInto(out *AutonomousDatabaseSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutonomousDatabaseSpec.
func (in *AutonomousDatabaseSpec) DeepCopy() *AutonomousDatabaseSpec {
	if in == nil {
		return nil
	}
	out := new(AutonomousDatabaseSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutonomousDatabaseStatus) DeepCopyInto(out *AutonomousDatabaseStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutonomousDatabaseStatus.
func (in *AutonomousDatabaseStatus) DeepCopy() *AutonomousDatabaseStatus {
	if in == nil {
		return nil
	}
	out := new(AutonomousDatabaseStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LongTermBackupScheduleInitParameters) DeepCopyInto(out *LongTermBackupScheduleInitParameters) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.RepeatCadence != nil {
		in, out := &in.RepeatCadence, &out.RepeatCadence
		*out = new(string)
		**out = **in
	}
	if in.RetentionPeriodInDays != nil {
		in, out := &in.RetentionPeriodInDays, &out.RetentionPeriodInDays
		*out = new(float64)
		**out = **in
	}
	if in.TimeOfBackup != nil {
		in, out := &in.TimeOfBackup, &out.TimeOfBackup
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LongTermBackupScheduleInitParameters.
func (in *LongTermBackupScheduleInitParameters) DeepCopy() *LongTermBackupScheduleInitParameters {
	if in == nil {
		return nil
	}
	out := new(LongTermBackupScheduleInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LongTermBackupScheduleObservation) DeepCopyInto(out *LongTermBackupScheduleObservation) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.RepeatCadence != nil {
		in, out := &in.RepeatCadence, &out.RepeatCadence
		*out = new(string)
		**out = **in
	}
	if in.RetentionPeriodInDays != nil {
		in, out := &in.RetentionPeriodInDays, &out.RetentionPeriodInDays
		*out = new(float64)
		**out = **in
	}
	if in.TimeOfBackup != nil {
		in, out := &in.TimeOfBackup, &out.TimeOfBackup
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LongTermBackupScheduleObservation.
func (in *LongTermBackupScheduleObservation) DeepCopy() *LongTermBackupScheduleObservation {
	if in == nil {
		return nil
	}
	out := new(LongTermBackupScheduleObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LongTermBackupScheduleParameters) DeepCopyInto(out *LongTermBackupScheduleParameters) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.RepeatCadence != nil {
		in, out := &in.RepeatCadence, &out.RepeatCadence
		*out = new(string)
		**out = **in
	}
	if in.RetentionPeriodInDays != nil {
		in, out := &in.RetentionPeriodInDays, &out.RetentionPeriodInDays
		*out = new(float64)
		**out = **in
	}
	if in.TimeOfBackup != nil {
		in, out := &in.TimeOfBackup, &out.TimeOfBackup
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LongTermBackupScheduleParameters.
func (in *LongTermBackupScheduleParameters) DeepCopy() *LongTermBackupScheduleParameters {
	if in == nil {
		return nil
	}
	out := new(LongTermBackupScheduleParameters)
	in.DeepCopyInto(out)
	return out
}
